import os
from huggingface_hub import InferenceClient


HF_TOKEN = os.environ.get("HF_TOKEN")
if not HF_TOKEN:
    raise ValueError("Set your HF_TOKEN environment variable with your Hugging Face API key.")


hf_client = InferenceClient(
    provider="nscale",  
    api_key=HF_TOKEN
)

def verify_with_hf_llm(llm1_output: str, context_description: str, current_exercise: str, next_exercise: str, dialogue_history: list) -> str:
    """
    Vérifie la sortie du LLM principal avec un second LLM plus neutre.
    """

    history_str = "\n".join(dialogue_history)

    verifier_prompt = f"""
You are an assistant responsible for verifying and correcting responses generated by another language model (StretchBot) during a stretching coaching session.

The original prompt given to the first model (StretchBot) included the current exercise, the next one, the user context (physical and emotional state), and a knowledge graph.

Your task:
1. Read the output generated by StretchBot.
2. Verify that the output follows the instructions given to StretchBot:
   - If the exercise status is "success", it's okay to propose the next exercise using "NEXT_EXERCISE: ..."
   - If the status is "not yet", it should encourage the user, not skip ahead.
   - The response must not repeat offers already refused in the dialogue history.
   - It should start with POINT_ if referring to a detected object.
   - It should start with STOP_ROUTINE if stopping the session.
   - The reply must be friendly, brief, and supportive.
3. If the output incorrectly uses 'NEXT_EXERCISE', remove this prefix and rewrite the entire sentence as a friendly and encouraging continuation of the current exercise, without skipping ahead.
4. If other corrections are needed (clarity, empathy), also improve them.
5. If the output is fine, repeat it exactly.

Context:
{context_description}

Current exercise: {current_exercise}
Next exercise: {next_exercise}

Dialogue history:
{history_str}

StretchBot output to evaluate:
\"\"\"
{llm1_output}
\"\"\"

Format your reply like this and only once:

CorrectedOutput: <corrected or confirmed output here>
Reasoning: <explanation of the correctness or correction>
"""

    response = hf_client.chat.completions.create(
        model="Qwen/Qwen3-8B",
        messages=[{"role": "user", "content": verifier_prompt}]
    )
    return response.choices[0].message.content


"""
if __name__ == "__main__":
    # Exemple de variables à remplacer par ton contexte réel
    context_description = "Exercise status: success"
    current_exercise = "Stretch your arms above your head"
    next_exercise = "Touch your toes"
    dialogue_history = [
        "Human: I'm feeling pretty good today!",
        "Robot: Awesome! Let's get started with the stretching."
    ]
    llm1_output = "Great job! Now let's move to the next exercise."

    verifier_reply = verify_with_hf_llm(
        llm1_output,
        context_description=context_description,
        current_exercise=current_exercise,
        next_exercise=next_exercise,
        dialogue_history=dialogue_history
    )
    print(verifier_reply)
    """
